/*
 * This source file was generated by the Gradle 'init' task
 */
package org.admin;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.PropertySource;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.bind.annotation.GetMapping;

@SpringBootApplication
@EnableTransactionManagement
@PropertySource({
        "classpath:config/ncp.properties",
        "classpath:config/ncp-secret.properties"
})

public class App {
    public static void main(String[] args) {
        System.out.println("한달살기 관리자 시스템 실행");
        SpringApplication.run(App.class, args);
    }

}
