/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package salaba;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.PropertySource;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.bind.annotation.GetMapping;

@SpringBootApplication
@EnableTransactionManagement
<<<<<<< HEAD
=======
@PropertySource({
    "classpath:config/ncp.properties",
    "classpath:config/ncp-secret.properties"
})
>>>>>>> ec5f381085fc7be6c91345a11d9923fe80148ce1
@Controller
public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("Salaba 시스템 서버 실행!");
        SpringApplication.run(App.class, args);
    }

    @GetMapping("/home")
    public void home() {
<<<<<<< HEAD
=======
    }

    @GetMapping("/about")
    public void about() {
>>>>>>> ec5f381085fc7be6c91345a11d9923fe80148ce1
    }
}
